#!/bin/sh
base="lastlogin"
stats() {
  lastlogin | awk -v q='"' -v base="$base" '
    BEGIN {
      print "# HELP " base " Last login of user."
      print "# TYPE " base " gauge"
    }
    {
      param = "{user=" q $1 q "} "
      last = 0
      if (match($0, /(Mon|Tue|Wed|Thu|Fri|Sat|Sun) [A-Z][a-z][a-z] +[0-9]+ [0-9:]+ 2[0-9]+$/) > 0) {
        "date -j -f " q "%a %b %d %T %Y" q " " q substr($0, RSTART, RLENGTH) q " +%s" | getline last
      }
      print base param last
    }
  '
}
if [ -z "$1" ]; then
  stats
else
  stats > "$1.tmp"
  mv "$1.tmp" "$1"
fi
